create forgotpassword sequence and refresh css for sendPasswordResetE…
WildCodeSchool/cdajs-2405-projet-la-meute pull request #26
Opened 2024-12-27 18:54 UTC by Dolpheus89

Création du diagramme de séquence pour la fonctionnalité "mot de passe oublié".
Mise à jour du CSS du mail pour la réinitialisation du mot de passe dans EmailService (CSS en ligne - CSS2).

voir photos avant/apres 

![Capture d’écran du 2024-12-20 11-36-35](https://github.com/user-attachments/assets/4bc157bf-5678-49e1-842b-d78c27208f81)
![Capture d’écran du 2024-12-27 18-02-23](https://github.com/user-attachments/assets/cda7e9db-5487-452d-98fc-84c55aa5cf9c)

2025-01-03 08:44 UTC, FlorenceBuchelet requested changes
Les contrastes du mail ne sont pas tous accessibles mais sinon du bon boulot !
Je ne suis pas contre un petit eclaircissement du schéma, c'est sans doute moi qui ai mal compris.

2025-01-03 08:44 UTC, FlorenceBuchelet commented on _ressources/conception_ressources/assets/mails/Forgotpassword.png
Le contraste des textes en vert et orange ne sont pas accessibles :)

2025-01-03 08:44 UTC, FlorenceBuchelet commented on _ressources/conception_ressources/assets/sequences/ForgotPassword.svg
En anglais on dit toujours "email", un "mail" c'est un courrier. Attention aussi à différencier email et email address, parler d'email pour une adresse est un abus de langage qui peut amener à des quiproquos !

Le reset token est stocké en BDD ? J'ai l'impression qu'il manque un petit morceau : est-ce que le reset token est stocké ET envoyé au serveur à sa création ? ou dans le reset email ? Je comprends pas bien.

2025-01-08 16:44 UTC, Melprcllr approved these changes

2025-01-09 14:34 UTC, FlorenceBuchelet approved these changes

2025-01-09 14:35 UTC, merged